# Generated by Django 6.1.1 on 2026-09-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_category_book_added_by_movie_added_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1 - Çok kötü"),
                    (2, "2 - Kötü"),
                    (3, "3 - Orta"),
                    (4, "4 - İyi"),
                    (5, "5 - Mükemmel"),
                ],
                verbose_name="Puan",
            ),
        ),
    ]
