# Generated by Django 6.1.1 on 2026-10-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_alter_review_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="wiki_image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="wiki_image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
